lighting_config:
  brightness: 0.5
  fade: 0.2
  steps_per_transistion: 1000

audio_config:
  trigger_style: "max"
  bass_threshold: 0.8
  bass_lower_bound: 0
  bass_upper_bound: 200
  mid_threshold: 0.5
  mid_lower_bound: 800
  mid_upper_bound: 3000



  
