0:
  auto_cycle: 1
  bass_debounce: 6.938893903907228e-17
  bass_lower_bound: 30
  bass_threshold: 0.20000000000000004
  bass_upper_bound: 300
  brightness: 0.6
  current_step: 1741
  fade: 0.08
  fade_out_threshold: 60
  length_mid_strobe: 30
  mid_debounce: 0.3
  mid_lower_bound: 1400
  mid_threshold: 0.20000000000000004
  mid_upper_bound: 2000
  state: 2
  steps_per_transition: 1520
  time_per_mode: 60
  trigger_style: max
1:
  auto_cycle: 1
  bass_debounce: 6.938893903907228e-17
  bass_lower_bound: 30
  bass_threshold: 0.20000000000000004
  bass_upper_bound: 300
  brightness: 0.6
  current_step: 2651
  fade: 0.08
  fade_out_threshold: 60
  length_mid_strobe: 30
  mid_debounce: 0.3
  mid_lower_bound: 1400
  mid_threshold: 0.20000000000000004
  mid_upper_bound: 2000
  state: 2
  steps_per_transition: 1520
  time_per_mode: 60
  trigger_style: max
2:
  auto_cycle: 1
  bass_debounce: 1.3877787807814457e-17
  bass_lower_bound: 30
  bass_threshold: 0.20000000000000004
  bass_upper_bound: 300
  brightness: 0.6
  current_step: 3078
  fade: 0.08
  fade_out_threshold: 60
  length_mid_strobe: 30
  mid_debounce: 0.3
  mid_lower_bound: 1400
  mid_threshold: 0.20000000000000004
  mid_upper_bound: 2000
  state: 2
  steps_per_transition: 1120
  time_per_mode: 60
  trigger_style: max
3:
  auto_cycle: 1
  bass_debounce: 1.3877787807814457e-17
  bass_lower_bound: 30
  bass_threshold: 0.20000000000000004
  bass_upper_bound: 300
  brightness: 0.6
  current_step: 3034
  fade: 0.08
  fade_out_threshold: 60
  length_mid_strobe: 30
  mid_debounce: 0.3
  mid_lower_bound: 1400
  mid_threshold: 0.20000000000000004
  mid_upper_bound: 2000
  state: 2
  steps_per_transition: 1120
  time_per_mode: 60
  trigger_style: max
