auto_cycle: 0
bass_debounce: 1.3877787807814457e-17
bass_lower_bound: 30
bass_threshold: 0.4
bass_upper_bound: 300
brightness: 0.5
current_step: 684
fade: 0.04
fade_out_threshold: 60
length_mid_strobe: 30
mid_debounce: 0.3
mid_lower_bound: 500
mid_threshold: 0.20000000000000004
mid_upper_bound: 3000
state: 1
steps_per_transition: 1120
time_per_mode: 10
trigger_style: max
