- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.103.198
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.103.219
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.103.156
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.103.154
