- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.153.198
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.153.219
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.153.156
- edit_config: 1
  fps: 40
  num_bars: 1
  target_ip: 192.168.153.154
