- edit_config: 1
  fps: 60
  num_bars: 5
  target_ip: 192.168.1.103
- edit_config: 1
  fps: 60
  num_bars: 5
  target_ip: 192.168.1.102
- edit_config: 1
  fps: 60
  num_bars: 5
  target_ip: 192.168.1.104
- edit_config: 1
  fps: 60
  num_bars: 5
  target_ip: 192.168.1.105
