- audio_reactive: false
  auto_cycle: true
  name: Static
- audio_reactive: true
  auto_cycle: false
  name: Beat Detector
- audio_reactive: true
  auto_cycle: false
  name: Pulse
- audio_reactive: true
  auto_cycle: true
  name: Bass Strobe
- audio_reactive: true
  auto_cycle: false
  name: Bass & Mid Strobe
- audio_reactive: true
  auto_cycle: false
  name: Sine Wave
- audio_reactive: true
  auto_cycle: false
  name: Swirl

